name: Comment
on:
  issue_comment:
    types: [created, edited]
jobs:
  job1:
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'Run test' && github.event.issue.pull_request
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
      - name: script_label
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['my-label']
            })