name: Comment
on:
  issue_comment:
    types: [created, edited]
jobs:
  job1:
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'Run test' && github.event.issue.pull_request
    steps:
      - run: |
          echo "PR_NUMBER=${{github.event.issue.number}}" > number
          echo "PR_NUMBER=${{github.event.issue.number}}" >> $GITHUB_ENV
      - name: script_label
        uses: actions/github-script@v6
        with:
          script: |
              let PR = await github.rest.pulls.get({
                pull_number: ${{env.PR_NUMBER}},
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              core.exportVariable('PR_BODY', PR);
      - run: |
          echo ${{toJSON(env.PR_BODY)}}
      - name: Set env variables if there is a PR
        run: |
          cat <<EOT >> environment
          SYSTEM_PULLREQUEST_TARGETBRANCH=${{ env.PR.base.ref }}
          SYSTEM_PULLREQUEST_SOURCEBRANCH=${{ env.PR.head.ref }}
          SYSTEM_PULLREQUEST_PULLREQUESTID=${{ env.PR.id }}
          SYSTEM_PULLREQUEST_SOURCECOMMITID=${{ env.PR.head.sha }}
          DEPLOYBASEPATH=pull/${{env.PR.number}}
          DEPLOYURL=https://${{env.DEPLOYHOST}}/pull/${{env.PR.number}}
          EOT
          EOT
        if: ${{!startsWith(github.ref, 'refs/pull/')}}

      - name: Define env variables
        run: |
          input_file="environment"
          while read line
          do
          echo "$line" >> $GITHUB_ENV
          done < "$input_file"
      - run: |
          printenv | sort
      - uses: actions/upload-artifact@v2
        with:
            name: pr_number
            path: number