name: Comment
on:
  issue_comment:
    types: [created, edited]
jobs:
  job1:
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'Run test'
    steps:
    - name: Dump GitHub context
      id: github_context_step
      run: echo '${{ toJSON(github) }}'
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labels.yml  