name: Comment
on:
  issue_comment:
    types: [created, edited]
jobs:
  job1:
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'Run test' && github.event.issue.pull_request
    steps:
      - run: |
          echo "PR_NUMBER=${{github.event.issue.number}}" > number
          echo "PR_NUMBER=${{github.event.issue.number}}" >> $GITHUB_ENV
      - name: script_label
        uses: actions/github-script@v6
        with:
          script: |
              let PR = await github.rest.pulls.get({
                pull_number: ${{env.PR_NUMBER}},
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              core.exportVariable('SYSTEM_PULLREQUEST_TARGETBRANCH', PR.data.base.ref);
              core.exportVariable('SYSTEM_PULLREQUEST_SOURCEBRANCH', PR.data.head.ref);
              core.exportVariable('SYSTEM_PULLREQUEST_PULLREQUESTID', PR.data.id);
              core.exportVariable('SYSTEM_PULLREQUEST_SOURCECOMMITID', PR.data.head.sha);
              core.exportVariable('DEPLOYBASEPATH', PR.data.number);
              core.exportVariable('DEPLOYURL', PR.data.number);
  
      - run: |
          printenv | sort
      - uses: actions/upload-artifact@v2
        with:
            name: pr_number
            path: number