name: learn-github-actions
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: echo "DUMM=val1" >> $GITHUB_ENV
      - run: printenv | sort

  second:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: echo "DUMM=val2" >> $GITHUB_ENV
      - name: Download skip screener artifact
        uses: actions/github-script@v6
        with:
          script: |
            let matchArtifact = undefined
            if(!matchArtifact)
              return 'false'
            return 'true'
          result-encoding: string

      - name: Get result
        run: echo "RESULT=${{steps.set-result.outputs.result}}" >> $GITHUB_ENV

      - run: printenv | sort

  third:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: echo "DUMM=val3" >> $GITHUB_ENV
      - run: printenv | sort
      - run: |
          echo "HELLO"
        if: ${{env.DUMM == val3}}