name: second comm

on:
  workflow_run:
    workflows:
      - Comment
    types:
      - completed

jobs:
  Action:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: script_label
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.PAT}}
        script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['my-label']
            })
