name: action-2

on:
  workflow_run:
    workflows:
      - action-1
    types:
      - completed
env:
  SUPER_SECRET: ${{ secrets.TEST_SECRET }}
jobs:
  SecondAction:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download environment variables artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: first.yml
          workflow_conclusion: success
          name: art-artifact

      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - run: node test.js

      - run: |
          echo "EVRIKA"
        if: env.SUPER_SECRET == 'value'

      - run: |
          echo "$SECRET"
        env:
          SECRET: ${{ secrets.TEST_SECRET}}
      
      
