name: action-2

on:
  workflow_run:
    workflows:
      - action-1
    types:
      - completed

jobs:
  SecondAction:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - run: |
          echo "$SECRET"
        env:
          SECRET: ${{ secrets.TEST_SECRET}}