name: action-2

on:
  workflow_run:
    workflows:
      - action-1
    types:
      - completed

jobs:
  SecondAction:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
  
      - run: cat README.md
      - run: cat art
      - run: |
          echo "HELLO from second"
        if: ${{secrets.TEST_VALUE === secrets.TEST_VALUE}}